# Generated by Django 5.0.1 on 2024-01-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0003_alter_user_lastname2_alter_user_profile_picture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address_cat',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('d_codigo', models.CharField(max_length=100)),
                ('d_asenta', models.CharField(max_length=100)),
                ('d_tipo_asenta', models.CharField(max_length=100)),
                ('D_mnpio', models.CharField(max_length=100)),
                ('d_estado', models.CharField(max_length=100)),
                ('d_ciudad', models.CharField(max_length=100)),
                ('d_CP', models.CharField(max_length=100)),
                ('c_estado', models.CharField(max_length=100)),
                ('c_oficina', models.CharField(max_length=100)),
                ('c_CP', models.CharField(max_length=100)),
                ('c_tipo_asenta', models.CharField(max_length=100)),
                ('c_mnpio', models.CharField(max_length=100)),
                ('id_asenta_cpcons', models.CharField(max_length=100)),
                ('d_zona', models.CharField(max_length=100)),
                ('c_cve_ciudad', models.CharField(max_length=100)),
            ],
        ),
    ]
