# Generated by Django 5.0.1 on 2024-01-19 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('lastname1', models.CharField(max_length=45)),
                ('lastname2', models.CharField(max_length=45, null=True)),
                ('username', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=128)),
                ('profile_picture', models.CharField(max_length=255, null=True)),
                ('birthdate', models.DateField()),
                ('creation_date', models.DateTimeField()),
                ('update_date', models.DateTimeField(null=True)),
                ('role', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.RESTRICT, to='aplicacion.user_role')),
            ],
        ),
    ]
