# Generated by Django 5.0.1 on 2024-01-24 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Direccion_cat',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('d_codigo', models.CharField(max_length=100)),
                ('d_asenta', models.CharField(max_length=100)),
                ('d_tipo_asenta', models.CharField(max_length=100)),
                ('D_mnpio', models.CharField(max_length=100)),
                ('d_estado', models.CharField(max_length=100)),
                ('d_ciudad', models.CharField(max_length=100)),
                ('d_CP', models.CharField(max_length=100)),
                ('c_estado', models.CharField(max_length=100)),
                ('c_oficina', models.CharField(max_length=100)),
                ('c_CP', models.CharField(max_length=100)),
                ('c_tipo_asenta', models.CharField(max_length=100)),
                ('c_mnpio', models.CharField(max_length=100)),
                ('id_asenta_cpcons', models.CharField(max_length=100)),
                ('d_zona', models.CharField(max_length=100)),
                ('c_cve_ciudad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=250)),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.RESTRICT, to='aplicacion.category')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=45)),
                ('place', models.ForeignKey(db_column='place_id', on_delete=django.db.models.deletion.RESTRICT, to='aplicacion.place')),
            ],
        ),
        migrations.CreateModel(
            name='Address_place',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=45)),
                ('zip_code', models.IntegerField()),
                ('state', models.CharField(max_length=45)),
                ('region', models.CharField(max_length=45)),
                ('colony', models.CharField(max_length=45)),
                ('street', models.CharField(max_length=50)),
                ('ext_number', models.IntegerField()),
                ('int_number', models.IntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('place', models.ForeignKey(db_column='place_id', on_delete=django.db.models.deletion.RESTRICT, to='aplicacion.place')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('comment_content', models.CharField(max_length=250)),
                ('score', models.FloatField()),
                ('place', models.ForeignKey(db_column='place_id', on_delete=django.db.models.deletion.RESTRICT, to='aplicacion.place')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.RESTRICT, to='aplicacion.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('like', models.IntegerField()),
                ('dislike', models.IntegerField()),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.RESTRICT, to='aplicacion.user')),
                ('rating', models.ForeignKey(db_column='rating_id', on_delete=django.db.models.deletion.RESTRICT, to='aplicacion.rating')),
            ],
        ),
    ]
