# Generated by Django 5.0.1 on 2024-01-25 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_category_direccion_cat_place_picture_address_place_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='content',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='comment_content',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='place',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='score',
        ),
        migrations.AddField(
            model_name='picture',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='rating',
            name='dislike',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='like',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='address_place',
            name='ext_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='address_place',
            name='int_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='address_place',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='address_place',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('comment', models.CharField(max_length=250, null=True)),
                ('score', models.FloatField()),
                ('place', models.ForeignKey(db_column='place_id', on_delete=django.db.models.deletion.RESTRICT, to='aplicacion.place')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.RESTRICT, to='aplicacion.user')),
            ],
        ),
        migrations.AddField(
            model_name='rating',
            name='review',
            field=models.ForeignKey(db_column='review_id', null=True, on_delete=django.db.models.deletion.RESTRICT, to='aplicacion.review'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
